features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  logo: true
  name: true
  node_user_picture: 1
  slogan: true
facebook_url: 'https://www.facebook.com/zymphonies'
twitter_url: 'https://twitter.com/zymphonies'
google_plus_url: 'https://plus.google.com/+ZymphoniesTechnologies'
linkedin_url: 'http://www.linkedin.com/company/zymphonies'
pinterest_url: 'https://www.pinterest.com/zymphonies/'
rss_url: rss.xml
show_social_icon: 1
show_credit_link: 1
show_slideshow: 1
no_of_slides: '3'
slide_title_1: 'UMIT- EMPOWERING THE WOMEN'
slide_description_1: ''
slide_url_1: '#'
slide_image_path_1: /images/slider/slide_01.jpg
slide_title_2: 'A bright future awaits'
slide_description_2: ''
slide_url_2: '#'
slide_image_path_2: /images/slider/slide_02.jpg
_core:
  default_config_hash: TCnsvjszngwaTxzCilUk5_D2oxTo2EyAXpgC8yaDmZs
logo:
  use_default: 0
  path: 'public://umit logo.jpeg'
favicon:
  use_default: 1
slide_image_path1:
  - '39'
slide_image_path2:
  - '55'
slide_image_path3:
  - '56'
slide_title_3: ''
slide_description_3: ''
slide_url_3: ''
